-- Auto-Payroll via TIP-1011 access keys (Subscriptions on Tempo).
--
-- Each row is one "authorization": an employer has signed a KeyAuthorization
-- onchain that lets a Remlo-controlled access key spend at most `per_period_amount`
-- of `token_address` per `period_seconds` from their treasury, scoped to a
-- specific PayrollBatcher contract + selector. The cron enumerates active rows
-- on each tick and, when a row is "due" (last_run_at + period <= now), runs a
-- payroll cycle on the employer's behalf.
--
-- The access key itself (private key + public address) is generated by Remlo
-- and stored encrypted-at-rest. The chain knows only the public address; the
-- employer's signature delegates spending authority to that public address.
--
-- Lifecycle:
--   draft        - employer opened the flow but hasn't signed yet (UI state)
--   active       - on-chain authorize tx confirmed; cron picks up
--   paused       - employer manually paused; cron skips (but auth is still on-chain)
--   revoked      - employer signed revokeKey; cron skips, ignored on-chain
--   expired      - past its expires_at; cron skips
--   failed       - last cycle reverted on-chain (e.g. cap exceeded); cron pauses
--                  pending operator review

CREATE TABLE IF NOT EXISTS autopayroll_authorizations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  employer_id uuid NOT NULL REFERENCES employers(id) ON DELETE CASCADE,

  status text NOT NULL DEFAULT 'draft' CHECK (status IN (
    'draft', 'active', 'paused', 'revoked', 'expired', 'failed'
  )),

  -- The access-key public address that the employer authorized. Spending
  -- happens FROM this key's perspective onchain — the chain's spending-limit
  -- bookkeeping is keyed on (employer_treasury, accessKeyAddress).
  access_key_address text NOT NULL CHECK (access_key_address ~ '^0x[0-9a-fA-F]{40}$'),

  -- Encrypted private key for the access key (sealed-box style). Plain
  -- jsonb so the encryption shape can evolve without a schema migration.
  -- See lib/tempo/access-keys.ts for the encryption envelope.
  access_key_encrypted jsonb NOT NULL,

  -- The TIP-20 we're allowed to spend (pathUSD by default).
  token_address text NOT NULL CHECK (token_address ~ '^0x[0-9a-fA-F]{40}$'),

  -- Per-period spending cap (raw uint256 string so we can hold values
  -- larger than JS number).
  per_period_amount text NOT NULL,

  -- Period in seconds. Tempo today supports fixed durations (e.g. 86400 for
  -- 1 day, 604800 for 1 week). Calendar months land in a future T-upgrade.
  period_seconds bigint NOT NULL CHECK (period_seconds >= 3600),

  -- Onchain expiry (unix seconds). Cron stops issuing transfers past this.
  expires_at_unix bigint NOT NULL,

  -- The PayrollBatcher contract we're scoped to call (often Remlo's address
  -- but per-employer in a future model where employers run their own batcher).
  scoped_target text NOT NULL CHECK (scoped_target ~ '^0x[0-9a-fA-F]{40}$'),
  -- The 4-byte function selector we're scoped to. Stored as full bytes32 for
  -- alignment with onchain encoding; only first 4 bytes are significant.
  scoped_selector text NOT NULL CHECK (scoped_selector ~ '^0x[0-9a-fA-F]{8}$'),

  -- Onchain proof: tx hash of the `authorizeKey` call.
  authorize_tx_hash text,
  -- Onchain proof: tx hash of `revokeKey` (when revoked).
  revoke_tx_hash text,

  -- Bookkeeping for the cron.
  last_run_at timestamptz,
  last_run_status text,
  last_run_tx_hash text,
  last_run_error text,
  cycles_executed integer NOT NULL DEFAULT 0,

  -- Free-text reason employer gave when pausing or as note at creation.
  notes text CHECK (notes IS NULL OR length(notes) <= 1000),

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- One active authorization per (employer, access_key_address) — prevents the
-- cron from picking the same key twice if a UI bug double-creates.
CREATE UNIQUE INDEX IF NOT EXISTS idx_autopayroll_unique_active_key
  ON autopayroll_authorizations (employer_id, access_key_address)
  WHERE status IN ('draft', 'active', 'paused');

-- Hot-path index for the cron tick query: "active rows that are due now".
CREATE INDEX IF NOT EXISTS idx_autopayroll_active_due
  ON autopayroll_authorizations (status, last_run_at NULLS FIRST)
  WHERE status = 'active';

CREATE OR REPLACE FUNCTION autopayroll_authorizations_touch_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS autopayroll_authorizations_touch_updated_at
  ON autopayroll_authorizations;
CREATE TRIGGER autopayroll_authorizations_touch_updated_at
  BEFORE UPDATE ON autopayroll_authorizations
  FOR EACH ROW
  EXECUTE FUNCTION autopayroll_authorizations_touch_updated_at();

ALTER TABLE autopayroll_authorizations ENABLE ROW LEVEL SECURITY;
-- Reads/writes via service role only; the API enforces auth via getAuthorizedEmployer.
