/**
 * lib/mcp/oauth/crypto.ts — Web Crypto helpers for the Remlo MCP OAuth flow.
 *
 * Stays runtime-agnostic (Web Crypto only) so it works on Edge runtimes
 * if we ever migrate. ES256 (P-256) is chosen to match Privy's algorithm —
 * downstream Tier 2 verification already uses Web Crypto P-256 via
 * `lib/jwt.ts`, so importing those primitives keeps the surface small.
 *
 * Three responsibilities live here:
 *
 *   1. Loading our ES256 keypair from env (PEM-encoded).
 *   2. Signing and verifying compact JWTs (header.payload.signature).
 *   3. Generating + validating PKCE S256 challenges.
 *
 * Symmetric keys are not used. Refresh tokens are opaque random strings
 * generated by `randomToken()` and stored in Supabase, not JWTs.
 */

const ENCODER = new TextEncoder()
const DECODER = new TextDecoder()

// ---------- Base64URL helpers ----------

function bytesToBase64Url(bytes: Uint8Array): string {
  let bin = ''
  for (const byte of bytes) bin += String.fromCharCode(byte)
  return btoa(bin).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')
}

function base64UrlToBytes(input: string): Uint8Array {
  const b64 = input.replace(/-/g, '+').replace(/_/g, '/')
  const padded = b64.padEnd(b64.length + ((4 - (b64.length % 4)) % 4), '=')
  const bin = atob(padded)
  const bytes = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i)
  return bytes
}

// ---------- PEM loaders ----------

function decodePem(pem: string): Uint8Array {
  const body = pem
    .replace(/-----BEGIN [^-]+-----/g, '')
    .replace(/-----END [^-]+-----/g, '')
    .replace(/\s+/g, '')
  return base64UrlToBytes(body.replace(/\+/g, '-').replace(/\//g, '_'))
}

let cachedPrivateKey: Promise<CryptoKey> | null = null
let cachedPublicKey: Promise<CryptoKey> | null = null

export async function getOauthPrivateKey(): Promise<CryptoKey> {
  if (cachedPrivateKey) return cachedPrivateKey
  cachedPrivateKey = (async () => {
    const pem = process.env.MCP_OAUTH_PRIVATE_KEY
    if (!pem) {
      throw new Error('MCP_OAUTH_PRIVATE_KEY is not set; OAuth token issuance is disabled')
    }
    const pkcs8 = decodePem(pem.replace(/\\n/g, '\n')).buffer as ArrayBuffer
    return crypto.subtle.importKey(
      'pkcs8',
      pkcs8,
      { name: 'ECDSA', namedCurve: 'P-256' },
      false,
      ['sign'],
    )
  })()
  return cachedPrivateKey
}

export async function getOauthPublicKey(): Promise<CryptoKey> {
  if (cachedPublicKey) return cachedPublicKey
  cachedPublicKey = (async () => {
    const pem = process.env.MCP_OAUTH_PUBLIC_KEY
    if (!pem) {
      throw new Error('MCP_OAUTH_PUBLIC_KEY is not set; OAuth token verification is disabled')
    }
    const spki = decodePem(pem.replace(/\\n/g, '\n')).buffer as ArrayBuffer
    return crypto.subtle.importKey(
      'spki',
      spki,
      { name: 'ECDSA', namedCurve: 'P-256' },
      false,
      ['verify'],
    )
  })()
  return cachedPublicKey
}

// ---------- Compact JWT (ES256) ----------

export interface JwtClaims {
  iss?: string
  sub?: string
  aud?: string
  exp?: number
  iat?: number
  jti?: string
  scope?: string
  client_id?: string
  [key: string]: unknown
}

export async function signEs256Jwt(claims: JwtClaims): Promise<string> {
  const header = { alg: 'ES256', typ: 'JWT' }
  const headerB64 = bytesToBase64Url(ENCODER.encode(JSON.stringify(header)))
  const payloadB64 = bytesToBase64Url(ENCODER.encode(JSON.stringify(claims)))
  const signingInput = `${headerB64}.${payloadB64}`

  const key = await getOauthPrivateKey()
  const sig = await crypto.subtle.sign(
    { name: 'ECDSA', hash: 'SHA-256' },
    key,
    ENCODER.encode(signingInput),
  )
  return `${signingInput}.${bytesToBase64Url(new Uint8Array(sig))}`
}

export async function verifyEs256Jwt(token: string): Promise<JwtClaims | null> {
  if (!token || typeof token !== 'string') return null
  const parts = token.split('.')
  if (parts.length !== 3) return null
  const [headerB64, payloadB64, signatureB64] = parts

  let header: { alg?: string; typ?: string }
  try {
    header = JSON.parse(DECODER.decode(base64UrlToBytes(headerB64))) as typeof header
  } catch {
    return null
  }
  if (header.alg !== 'ES256') return null

  let claims: JwtClaims
  try {
    claims = JSON.parse(DECODER.decode(base64UrlToBytes(payloadB64))) as JwtClaims
  } catch {
    return null
  }
  if (claims.exp && claims.exp * 1000 < Date.now()) return null

  let key: CryptoKey
  try {
    key = await getOauthPublicKey()
  } catch {
    return null
  }

  const signingInput = `${headerB64}.${payloadB64}`
  const sig = base64UrlToBytes(signatureB64).buffer.slice(0) as ArrayBuffer
  let ok: boolean
  try {
    ok = await crypto.subtle.verify(
      { name: 'ECDSA', hash: 'SHA-256' },
      key,
      sig,
      ENCODER.encode(signingInput).buffer.slice(0) as ArrayBuffer,
    )
  } catch {
    return null
  }
  return ok ? claims : null
}

// ---------- PKCE S256 verification ----------
//
// `code_challenge_method=S256` per RFC 7636: server stores the
// `code_challenge` at /authorize, then at /token recomputes
//   base64url(SHA256(code_verifier))
// and compares to the stored challenge. We reject `plain` outright; the
// MCP spec drops support for plain in favor of S256.

export async function verifyPkceS256(verifier: string, challenge: string): Promise<boolean> {
  if (!verifier || verifier.length < 43 || verifier.length > 128) return false
  const digest = await crypto.subtle.digest('SHA-256', ENCODER.encode(verifier))
  const recomputed = bytesToBase64Url(new Uint8Array(digest))
  // Constant-time-ish compare: same length first, then byte equality.
  if (recomputed.length !== challenge.length) return false
  let diff = 0
  for (let i = 0; i < recomputed.length; i++) {
    diff |= recomputed.charCodeAt(i) ^ challenge.charCodeAt(i)
  }
  return diff === 0
}

// ---------- Random tokens ----------
//
// Auth codes (~32 bytes b64url) and refresh tokens (~48 bytes b64url) are
// opaque random strings, generated with crypto.getRandomValues. We don't
// store the raw entropy in JWT form because they're single-use / rotatable.

export function randomToken(byteLen = 32): string {
  const bytes = new Uint8Array(byteLen)
  crypto.getRandomValues(bytes)
  return bytesToBase64Url(bytes)
}
